apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: client1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operations:
          - Read
          - Write
      - resource:
          type: group
          name: client1-group
          patternType: literal
        operations:
          - Read
          - Write
