apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic2
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1

---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: client1-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: client2-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
